### ISSUE TITLE
Gradual replacement of PHP with Python/JS

### ISSUE THREAD

**Issue by DonaldTsang** [lainchan/lainchan#153]
A simple idea: avoiding PHP all together in favor of Node.js or Python...
Since the code is already >50% Javascript, might as well push forward to the other ~30%
Maybe every signal sent from server to client and back are all just JSON using the API.

**Comment by Appleman1234** [comment]
This isn't really practical, and has been attempted over 5 times in various languages, with none of the attempts reaching even 33% feature parity or having a migration path for the existing data or database schema.

You are welcome to try rewriting your own port of vichan to yet another Language, but it isn't really relevant to this project or an issue of this project that people can submit pull requests against.

**Comment by DonaldTsang** [comment]
@Appleman1234 I think I see a a potential replacement, https://github.com/fatchan/jschan
But he would really need some assistance to gain feature-parity TBH.

**Comment by DonaldTsang** [comment]
https://github.com/Floens/uchan is in Python, so less of a potential but still, a lot.

**Comment by Appleman1234** [comment]
The original feature parity list I compiled for the other people trying to write lainchan / vichan rewrites on 4th October 2016 was 

feature complete image board requirements for lainchan parity

- moderation dashboard
- new board creation
- board deletion and editing
- uses database
- user management
- themes or extensions
- reporting system / log
- moderation log
- ban list
- ban appeals
- search
- configuration editor
- user notes
- extensions for donate page
- extensions for stream page
- extensions for irc page
- extensions for rules page
- name, email, subject, spolier image, file ,oekaki
- trip codes
- sticky, lock , raw html
- file / post deletion and password
- banners support
- customisable header support
- moderation actions, delete, delete by ip, delete by ip all boards, ban, ban
- and delete, unsticky, sage, lock, move and edit
- support for post formatting
- support for reply linking
- image / file upload
- thumbnail image support
- ddt support for layer ?
- ImgOps iqdb
- word filters
- word / phrase blocking
- anonymous naming scheme
- board customization
- api probably 4chan api compatible or similar
- catalog extension
- overboard extensions
- recent posts
- css themes
- works with and without javascript
- is performant and secure
- hackable

Since then there are several new features that have been added to lainchan, including overboards and board aliases, keyboard navigation, thread merge , auto IP note generation, multiple file upload using URLs, server side syntax highlighting .

This isn't a complete list of vichan features, for attempts at that see the config.php in vichan and then audit the codebase. I have already investigated over 40 different alternative imageboard software solutions including the two you have linked, and I didn't find them to be suitable or at feature parity yet.

**Comment by DonaldTsang** [comment]
@Appleman1234 as you said, YET. It still takes work to get them to work on these new features.

**Comment by Appleman1234** [comment]
If you want to work on other projects to bring them to feature parity to vichan, then feel free to do so and commit your patches and pull requests against their repositories, as I said earlier this issue is closed because it isn't relevant to the current project and it isn't tractable enough to raise patches and pull requests against. 

All of the evaluations I have done to date, and that I do regularly (every 3 months or so), have indicated that it is currently easier to stick with supporting and developing this code base, rather than attempting to write either a full port or gradual port, but if you want to do either, then go ahead, if you are successful then maybe I will evaluate your image board software as a potential migration target in 3 to 6 months or at a later date.

**Comment by DonaldTsang** [comment]
@Appleman1234 if you have time this weekend, help me craft a feature list that is as complete as you have marked/recorded. Would like to share with other aspiring imageboard builders.

**Comment by Appleman1234** [comment]
@DonaldTsang: Please don't mention me again, you appear to ignoring my correspondence in this thread. I have to make time to do requirements analysis, it isn't free time, you can craft your own list, I already have provided my original list and some of the newer improvements. Unless you have an actual issue with the code base other than its choice of implementation language or you have patch to contribute, then your discussion doesn't belong in this issue or against this Github repository.

**Comment by DonaldTsang** [comment]
I am requesting this on the behalf of https://github.com/yatima1460/Kamina about the requirements necessary for creating a replacement.
