### ISSUE TITLE
You look like a bot (reCaptcha window doesn't appear)

### ISSUE THREAD

**Issue by gegtor** [lainchan/lainchan#159]
With 

```
$config['recaptcha'] = true;
$config['recaptcha_public'] = 'x';
$config['recaptcha_private'] = 'x';

$config['report_captcha'] = true;
```

reCaptcha v2 windows doesn't appear in post form and in report form
<img width="465" alt="Screenshot 2019-08-10 at 04 49 01" src="https://user-images.githubusercontent.com/10978723/62816592-30027a00-bb2a-11e9-9a42-48e8aa84589a.png">

I've got these errors in browser
<img width="1678" alt="Screenshot 2019-08-10 at 04 47 33" src="https://user-images.githubusercontent.com/10978723/62816567-fa5d9100-bb29-11e9-8f42-45ba2d02550a.png">

reCaptcha script fails to load with correct keys?

Everything was rebuild after applying new config

**Comment by Appleman1234** [comment]
Try now. Please note, we don't use recaptcha or any captcha on lainchan.org, so we don't test this functionality as extensively as other functionality. If this still doesn't work for you, I can look at upgrading the support to v3 instead of v2, or I can finish integrating an alternative that we were considering at one point (Securimage, as per https://github.com/lainchan/lainchan/pull/146, which I have accidently partially commited to master, but haven't updated install.sql or inc/lib yet.

**Comment by gegtor** [comment]
Post form works :)
But report form doesn't display captcha and reports You look like a bot error 
<img width="1081" alt="Screenshot 2019-08-10 at 17 01 52" src="https://user-images.githubusercontent.com/10978723/62823400-b2be2000-bb90-11e9-8298-b8971f5aea4b.png">

Also i have new errors here
<img width="755" alt="Screenshot 2019-08-10 at 17 02 14" src="https://user-images.githubusercontent.com/10978723/62823401-b2be2000-bb90-11e9-9d30-0b1c91ece439.png">

**Comment by Appleman1234** [comment]
Report form not working is already a known issue in upstream bug https://github.com/vichan-devel/vichan/issues/329 , as for your content security policy issues, that is a configuration issue of your content security on your webserver and isn't related to lainchan.

**Comment by gegtor** [comment]
Then it's fixed

You can close the issue
