### ISSUE TITLE
Your IP address is listed in rbl.efnetrbl.org

### ISSUE THREAD

**Issue by Realhumanbeing552** [lainchan/lainchan#178]
Hello,
So, as the name of this issue states, I got the following message while trying to make a first post on the imageboard which I successfully installed on my domain with this script. I understand the reason behind it -- I used the Tor browser. I tried to change stuff in configurations but didn't find anything like such an option, and also, I'm pretty bad at coding, so I didn't find anything in the code either. I understand that allowing Tor IPs on my website may cause negative stuff, and I understand that the creators of this imageboard script might not have wanted me to allow Tor IPs. However, I consider that my website should have this option as I value my privacy and the privacy of other anons. 
Please, if you know how to fix this issue, tell me! 
Thanks!

**Comment by Realhumanbeing552** [comment]
Hey, people! I have found the solution to this issue myself -- no need to worry now!
I just used the debug function from the configurations and found the [function] => checkDNSBL in the  post.php. After deleting it, I managed to post on my imageboard from a Tor IP! 
I don't think this goes against the rules the creators set for the users of this script. If it does -- well, ooops! 
(-;

**Comment by Appleman1234** [comment]
The real fix for this is to edit https://github.com/lainchan/lainchan/blob/master/inc/config.php or instance-config.php in the same directory which overrides it, which you can do using the Configuration option of the moderation dashboard or by using SSH and editing the file directly.  and set 
`$config['dnsbl'][] = array ()` or otherwise remove the default `$config['dnsbl'][] = 'rbl.efnetrbl.org';` entry.
