### ISSUE TITLE
Database error: The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by panfu28** [lainchan/lainchan#183]
pls help i reached step 4 of installation but im stuck with this error:
Database error: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client

Running on Ubuntu 20.04
MySQL 8.0.21

**Comment by panfu28** [comment]
My Mysql user is 'root'@'127.0.0.1' and im doing the install.php from a remote PC if that matters, in the 'user' field of the install.php i put 'root', should i put root@127.0.0.1? im new to databases and MySQL

**Comment by Appleman1234** [comment]
This has nothing do to with lainchan code base and is because of the default authentication plugin changing in MySQL 8. As for the resolution of your issue, see https://stackoverflow.com/questions/52364415/php-with-mysql-8-0-error-the-server-requested-authentication-method-unknown-to and https://stackoverflow.com/questions/50026939/php-mysqli-connect-authentication-method-unknown-to-the-client-caching-sha2-pa . E.g. Tell mysql to use mysql_native_password authentication instead of its new default auth sock.

As for the configuration values they should look like 
`$config['db']['server'] = 'localhost';
$config['db']['database'] = '<databasename>';
$config['db']['prefix'] = '';
$config['db']['user'] = 'root';
$config['db']['password'] =<passwordgoeshere>`
in inc/instance-config.php
