### ISSUE TITLE
Dev contribution inquiry

### ISSUE THREAD

**Issue by jewyti** [lainchan/lainchan#20]
Hey folks was wondering if there are certain dos and donts for the project. From an initial walkthrough gave me the impression that overall performance of the site may be slow _I haven't done benchmarks, but I will_. Any thoughts would be helpful though

**Comment by barrucadu** [comment]
Performance shouldn't be too bad because everything gets built and served as static html as an when things change. Having said that, optimisations are welcome (but should probably be sent upstream).

In general:

- If it's a lainchan-specific feature or something without much wider interest, feel free to do it and submit a pull request against this repo.
- If it's something with wider interest, do it against vichan, so all users of the software can benefit (and so we have an easier time keeping up to date).

Does that answer your question, @jewyti?
