### ISSUE TITLE
my site doesn't have a catalog and it doesn't have multiple pages

### ISSUE THREAD

**Issue by peteblank2** [lainchan/lainchan#208]
I installed lainchan php7.4 branch I think. 
Whenever I click on catalog it doesn't show the catalog and whenever I click on page 2 it doesn't show page 2.
My site is vipbiz.finance/lainchan/pleb

**Comment by Appleman1234** [comment]
To generate catalog.html, you need to have the catalog theme enabled , From select https://vipbiz.finance/mod.php?/dashboard.html Manage Themes, and ensure that catalog theme is configured , installed and able to generate the relevant catalog.html page ?

Browsing to https://vipbiz.finance/, shows that instead of enabling or configuring a home page , you have apache directory listing enabled, this is generally not something you want. You also don't seem to have the relevant pages being generated for your boards. You should be able to https://vipbiz.finance/lainchan/pleb/1.html and have it not 404.
